version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    command:
      - "postgres"
      - "-c"
      - "work_mem=200MB"
    # ports:
    #   - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 4001:80
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@1.com
      - PGADMIN_DEFAULT_PASSWORD=123

  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      # - .:/webpacker-example-app
      - .:/tkmoto2
    ports:
      - '127.0.0.1:3035:3035'      
      
  dev: &dev
    build: .
    depends_on:
      - db
      - pgadmin
      - webpacker
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes: 
      - .:/tkmoto2
      - .bundle:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    # environment:
      # - ASSIST_DOCTOR_BOT_TOKEN
      # - ASSIST_DOCTOR_HOST

  # prod:
  #   <<: *dev
  #   depends_on:
  #     - db
  #   ports:
  #     - 80:80
  #     - 443:443
  #   environment:
  #     - RAILS_ENV=production
  #     - RAILS_SERVE_STATIC_FILES=1
  #     - RAILS_MASTER_KEY
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 443 -b '0.0.0.0'"

volumes:
  pgdata:
     external: true