 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/oils", type: :request do
  # Oil. As you add validations to Oil, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Oil.create! valid_attributes
      get oils_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      oil = Oil.create! valid_attributes
      get oil_url(oil)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_oil_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      oil = Oil.create! valid_attributes
      get edit_oil_url(oil)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Oil" do
        expect {
          post oils_url, params: { oil: valid_attributes }
        }.to change(Oil, :count).by(1)
      end

      it "redirects to the created oil" do
        post oils_url, params: { oil: valid_attributes }
        expect(response).to redirect_to(oil_url(Oil.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Oil" do
        expect {
          post oils_url, params: { oil: invalid_attributes }
        }.to change(Oil, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post oils_url, params: { oil: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested oil" do
        oil = Oil.create! valid_attributes
        patch oil_url(oil), params: { oil: new_attributes }
        oil.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the oil" do
        oil = Oil.create! valid_attributes
        patch oil_url(oil), params: { oil: new_attributes }
        oil.reload
        expect(response).to redirect_to(oil_url(oil))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        oil = Oil.create! valid_attributes
        patch oil_url(oil), params: { oil: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested oil" do
      oil = Oil.create! valid_attributes
      expect {
        delete oil_url(oil)
      }.to change(Oil, :count).by(-1)
    end

    it "redirects to the oils list" do
      oil = Oil.create! valid_attributes
      delete oil_url(oil)
      expect(response).to redirect_to(oils_url)
    end
  end
end
